name: CD Pipeline
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn clean --batch-mode test deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Commit and push the badge (if it changed)
        env:
          GIT_USERNAME: SirSkaro
          GIT_EMAIL: SirSkaro-action@github.com
          DEPLOY_URL: github.com/SirSkaro/pokeapi-reactor
        run: |
          if [[ `git status --porcelain *.svg` ]]; then
            git config --local user.name "${{ env.GIT_USERNAME }}"
            git config --local user.email "${{ env.GIT_EMAIL }}"
            git add *.svg
            git commit -am "Autogenerated JaCoCo coverage badges"
            git push --force --quiet "https://${{ env.GIT_USERNAME }}:${{ secrets.GITHUB_TOKEN }}@${{ env.DEPLOY_URL }}" master:master
          fi
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/